In [3]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, classification_report
from pipetorch import DFrame

In [4]:
#Import Datasets
df = pd.read_csv("Generated Datasets/ingr_pivot_lunch_diner_noten.csv").set_index("recipe")
tags = pd.read_csv("Datasets Foodboost/tags.csv")

#Get rid of ingredients that aren't used at least 40 times.
ValidColumns = df.loc[:,df.sum() > 40][df.sum(axis=1) != 0]

In [5]:
recepten = list(df.columns)
tags = tags[tags['recipe'].str.contains('|'.join(recepten))]
tags_pivot = tags.pivot_table(values="recipe", index= tags.recipe, columns="tag", aggfunc="count")
tags_pivot= tags_pivot.fillna(0) 
tags_ValidColumns = tags_pivot.loc[:,tags_pivot.sum() > 20][tags_pivot.sum(axis=1) != 0]
tags_ValidColumns

/tmp/ipykernel_22011/1601361395.py:2: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  tags = tags[tags['recipe'].str.contains('|'.join(recepten))]


tag                                                 5-ingrediënten  \
recipe                                                               
 Andijviestamppot met gebakken salami                          0.0   
 Bietensoep met selderijroom                                   0.0   
 Libanese wraps met appel-koolsalade                           0.0   
 Plaattaart met gegrilde groenten en witte kaas                1.0   
 Sticky cauliflower (gegrilde bloemkoolroosjes)...             0.0   
...                                                            ...   
Zweedse gehaktballetjes                                        0.0   
Zweedse gehaktballetjes met room                               0.0   
Zweedse vegaballetjes met aardappel &amp; broccoli             0.0   
Zwitserse kaasfondue                                           0.0   
‘Nasi’ met Hollandse soepgroente                               1.0   

tag                                                 amerikaans  aziatisch  \
recipe                                                                      
 Andijviestamppot met gebakken salami                      0.0        0.0   
 Bietensoep met selderijroom                               0.0        0.0   
 Libanese wraps met appel-koolsalade                       0.0        0.0   
 Plaattaart met gegrilde groenten en witte kaas            0.0        0.0   
 Sticky cauliflower (gegrilde bloemkoolroosjes)...         0.0        0.0   
...                                                        ...        ...   
Zweedse gehaktballetjes                                    0.0        0.0   
Zweedse gehaktballetjes met room                           0.0        0.0   
Zweedse vegaballetjes met aardappel &amp; broccoli         0.0        0.0   
Zwitserse kaasfondue                                       0.0        0.0   
‘Nasi’ met Hollandse soepgroente                           0.0        1.0   

tag                                                 bakken  barbecue  \
recipe                                                                 
 Andijviestamppot met gebakken salami                  1.0       0.0   
 Bietensoep met selderijroom                           0.0       0.0   
 Libanese wraps met appel-koolsalade                   0.0       0.0   
 Plaattaart met gegrilde groenten en witte kaas        0.0       0.0   
 Sticky cauliflower (gegrilde bloemkoolroosjes)...     0.0       1.0   
...                                                    ...       ...   
Zweedse gehaktballetjes                                1.0       0.0   
Zweedse gehaktballetjes met room                       1.0       0.0   
Zweedse vegaballetjes met aardappel &amp; broccoli     1.0       0.0   
Zwitserse kaasfondue                                   0.0       0.0   
‘Nasi’ met Hollandse soepgroente                       0.0       0.0   

tag                                                 bijgerecht  biologisch  \
recipe                                                                       
 Andijviestamppot met gebakken salami                      0.0         0.0   
 Bietensoep met selderijroom                               0.0         0.0   
 Libanese wraps met appel-koolsalade                       0.0         0.0   
 Plaattaart met gegrilde groenten en witte kaas            0.0         0.0   
 Sticky cauliflower (gegrilde bloemkoolroosjes)...         1.0         0.0   
...                                                        ...         ...   
Zweedse gehaktballetjes                                    0.0         0.0   
Zweedse gehaktballetjes met room                           1.0         0.0   
Zweedse vegaballetjes met aardappel &amp; broccoli         0.0         0.0   
Zwitserse kaasfondue                                       0.0         0.0   
‘Nasi’ met Hollandse soepgroente                           0.0         0.0   

tag                                                 borrel  borrelhapje  \
recipe                                                      

# keukens voorspellen

In [6]:
keukens = ['amerikaans','aziatisch','chinees','engels','frans','grieks','hollands','indiaas','indonesisch','italiaans', 'japans','marokkaans','mediterraan', 'mexicaans', 'midden-oosters','scandinavisch','spaans','thais','zuid-amerikaans']
df1 = tags_ValidColumns[keukens]
df1["sum"] = df1[keukens].sum(axis = 1)
df1=df1[df1["sum"] == 1]
df1

/tmp/ipykernel_22011/2749081629.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1["sum"] = df1[keukens].sum(axis = 1)


tag                                                 amerikaans  aziatisch  \
recipe                                                                      
 Andijviestamppot met gebakken salami                      0.0        0.0   
'Burrito'-schotel met knapperige tortillapuntjes           0.0        0.0   
'Kapsalon' met&nbsp;vegetarische&nbsp;kipshoarm...         0.0        0.0   
'Pho' met mihoen en ribeye                                 0.0        1.0   
'Spaanse' surf &amp; turfspiesjes met pittige t...         0.0        0.0   
...                                                        ...        ...   
Zweedse balletjes                                          0.0        0.0   
Zweedse broodsalade                                        0.0        0.0   
Zweedse gehaktballetjes                                    0.0        0.0   
Zweedse gehaktballetjes met room                           0.0        0.0   
‘Nasi’ met Hollandse soepgroente                           0.0        1.0   

tag                                                 chinees  engels  frans  \
recipe                                                                       
 Andijviestamppot met gebakken salami                   0.0     0.0    0.0   
'Burrito'-schotel met knapperige tortillapuntjes        0.0     0.0    0.0   
'Kapsalon' met&nbsp;vegetarische&nbsp;kipshoarm...      0.0     0.0    0.0   
'Pho' met mihoen en ribeye                              0.0     0.0    0.0   
'Spaanse' surf &amp; turfspiesjes met pittige t...      0.0     0.0    0.0   
...                                                     ...     ...    ...   
Zweedse balletjes                                       0.0     0.0    0.0   
Zweedse broodsalade                                     0.0     0.0    0.0   
Zweedse gehaktballetjes                                 0.0     0.0    0.0   
Zweedse gehaktballetjes met room                        0.0     0.0    0.0   
‘Nasi’ met Hollandse soepgroente                        0.0     0.0    0.0   

tag                                                 grieks  hollands  indiaas  \
recipe                                                                          
 Andijviestamppot met gebakken salami                  0.0       1.0      0.0   
'Burrito'-schotel met knapperige tortillapuntjes       0.0       0.0      0.0   
'Kapsalon' met&nbsp;vegetarische&nbsp;kipshoarm...     0.0       1.0      0.0   
'Pho' met mihoen en ribeye                             0.0       0.0      0.0   
'Spaanse' surf &amp; turfspiesjes met pittige t...     0.0       0.0      0.0   
...                                                    ...       ...      ...   
Zweedse balletjes                                      0.0       0.0      0.0   
Zweedse broodsalade                                    0.0       0.0      0.0   
Zweedse gehaktballetjes                                0.0       0.0      0.0   
Zweedse gehaktballetjes met room                       0.0       0.0      0.0   
‘Nasi’ met Hollandse soepgroente                       0.0       0.0      0.0   

tag                                                 indonesisch  italiaans  \
recipe                                                                       
 Andijviestamppot met gebakken salami                       0.0        0.0   
'Burrito'-schotel met knapperige tortillapuntjes            0.0        0.0   
'Kapsalon' met&nbsp;vegetarische&nbsp;kipshoarm...          0.0        0.0   
'Pho' met mihoen en ribeye                                  0.0        0.0   
'Spaanse' surf &amp; turfspiesjes met pittige t...          0.0        0.0   
...                                                         ...        ...   
Zweedse balletjes                                           0.0        0.0   
Zweedse broodsalade                                         0.0        0.0   
Zweedse gehaktballetjes                                     0.0        0.0   
Zweedse gehaktballetjes met room                            0.0        

In [7]:
tags2 = tags[tags['tag'].str.contains('|'.join(keukens))]
recepten_1_tag = list(df1.index)
tags2 = tags2[tags2['recipe'].isin(recepten_1_tag)]
tags2 = tags2.iloc[:,1:]
tags2.sort_values('recipe')

recipe              tag
31841               Andijviestamppot met gebakken salami         hollands
13996   'Burrito'-schotel met knapperige tortillapuntjes  zuid-amerikaans
108    'Kapsalon' met&nbsp;vegetarische&nbsp;kipshoar...         hollands
39543                         'Pho' met mihoen en ribeye        aziatisch
20439  'Spaanse' surf &amp; turfspiesjes met pittige ...           spaans
...                                                  ...              ...
42961                                  Zweedse balletjes    scandinavisch
40502                                Zweedse broodsalade    scandinavisch
45948                            Zweedse gehaktballetjes    scandinavisch
25071                   Zweedse gehaktballetjes met room    scandinavisch
22006                   ‘Nasi’ met Hollandse soepgroente        aziatisch

[2803 rows x 2 columns]

In [8]:
tags2_ingr = pd.merge(df,tags2, how= 'inner',left_on= 'recipe', right_on = 'recipe')
tags2_ingr = tags2_ingr.set_index('recipe')
#tags2_ingr_copy = tags2_ingr.copy()
#even_smaller_df = tags2_ingr_copy.loc[:,tags2_ingr_copy.sum() > 10][tags2_ingr_copy.sum(axis=1) != 0]
#even_smaller_df
#{k: v for k, v in sorted(d.items(), key=lambda item: item[1])}
i=0
rand_dict = {}
while i < 3:
    gerecht = str(np.random.choice(list(df.index)))
    mening = int(input(str(i) + ': ' + gerecht))
    rand_dict[gerecht] = mening
    i=i+1
rand_dict

0: Gezonde kerstboombroodjes1
1: Groenterijke nasi met zelfgemaakte atjar1
2: Boerenkoolstamppot met rode paprika1


{'Gezonde kerstboombroodjes': 1,
 'Groenterijke nasi met zelfgemaakte atjar': 1,
 'Boerenkoolstamppot met rode paprika': 1}

In [9]:
tags2_ingr

(arachide)olie  \
recipe                                                               
 Andijviestamppot met gebakken salami                          0.0   
'Burrito'-schotel met knapperige tortillapuntjes               0.0   
'Kapsalon' met&nbsp;vegetarische&nbsp;kipshoarm...             0.0   
'Pho' met mihoen en ribeye                                     0.0   
10 minutennasi met ham en gebakken ei                          0.0   
...                                                            ...   
Zwartebonenstoof met tofu en gordita's                         0.0   
Zweedse balletjes                                              0.0   
Zweedse gehaktballetjes                                        0.0   
Zweedse gehaktballetjes met room                               0.0   
‘Nasi’ met Hollandse soepgroente                               0.0   

                                                    (herten)biefstukken  \
recipe                                                                    
 Andijviestamppot met gebakken salami                               0.0   
'Burrito'-schotel met knapperige tortillapuntjes                    0.0   
'Kapsalon' met&nbsp;vegetarische&nbsp;kipshoarm...                  0.0   
'Pho' met mihoen en ribeye                                          0.0   
10 minutennasi met ham en gebakken ei                               0.0   
...                                                                 ...   
Zwartebonenstoof met tofu en gordita's                              0.0   
Zweedse balletjes                                                   0.0   
Zweedse gehaktballetjes                                             0.0   
Zweedse gehaktballetjes met room                                    0.0   
‘Nasi’ met Hollandse soepgroente                                    0.0   

                                                    (houdbare) melk  \
recipe                                                                
 Andijviestamppot met gebakken salami                           0.0   
'Burrito'-schotel met knapperige tortillapuntjes                0.0   
'Kapsalon' met&nbsp;vegetarische&nbsp;kipshoarm...              0.0   
'Pho' met mihoen en ribeye                                      0.0   
10 minutennasi met ham en gebakken ei                           0.0   
...                                                             ...   
Zwartebonenstoof met tofu en gordita's                          0.0   
Zweedse balletjes                                               0.0   
Zweedse gehaktballetjes                                         0.0   
Zweedse gehaktballetjes met room                                0.0   
‘Nasi’ met Hollandse soepgroente                                0.0   

                                                    (magere) shoarmareepjes  \
recipe                                                                        
 Andijviestamppot met gebakken salami                                   0.0   
'Burrito'-schotel met knapperige tortillapuntjes                        0.0   
'Kapsalon' met&nbsp;vegetarische&nbsp;kipshoarm...                      0.0   
'Pho' met mihoen en ribeye                                              0.0   
10 minutennasi met ham en gebakken ei                                   0.0   
...                                                                     ...   
Zwartebonenstoof met tofu en gordita's                                  0.0   
Zweedse balletjes                                                       0.0   
Zweedse gehaktballetjes                                                 0.0   
Zweedse gehaktballetjes met room                                        0.0   
‘Nasi’ met Hollandse soepgroente                                        0.0   

                                                    (olijf)olie  \
recipe                                                            
 Andijviestamppot met gebakken salami                       0.0   
'Burrito'-sc

In [209]:
X = tags2_ingr.iloc[:,:-1]
y = tags2_ingr.iloc[:,-1]

In [210]:
#Generate X_train, X_test, y_train, y_test
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)#, random_state=42)

In [211]:
#Import Decision Tree Classifier
from sklearn import tree

#Create and fit Decision Tree Classifier
clf = tree.DecisionTreeClassifier(max_depth = 3).fit(X_train, y_train)

#Create predictions of Decision Tree Classifier
clf_y_pred =  clf.predict(X_test)

#Print confusion matrix and classification report
print(confusion_matrix(y_test, clf_y_pred))
print(classification_report(y_test, clf_y_pred))

[[  0   1   0   0   0   0  16   0   0   0   0   0   0   0]
 [  0  54   0   0   0   1  30   0   0   0   0   0   0   0]
 [  0   1   0   0   0   0   3   0   0   0   0   0   0   0]
 [  0   1   0   0   0   0  26   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   5   0   0   0   0   0   0   0]
 [  0   6   0   0   0  25  84   0   0   0   0   0   0   0]
 [  0   4   0   0   0   2 159   0   0   0   0   0   0   0]
 [  0   2   0   0   0   0   7   0   0   0   0   0   0   0]
 [  0   4   0   0   0   0  40   0   0   0   0   0   0   0]
 [  0   8   0   0   0   0  31   0   0   0   0   0   0   0]
 [  0   8   0   0   0   0  13   0   0   0   0   0   0   0]
 [  0   1   0   0   0   0   4   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   9   0   0   0   0   0   0   0]
 [  0   2   0   0   0   0   6   0   0   0   0   0   0   0]]
                 precision    recall  f1-score   support

     amerikaans       0.00      0.00      0.00        17
      aziatisch       0.59      0.64      0.61        85
 

/opt/jupyterhub/anaconda/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1334: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/jupyterhub/anaconda/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1334: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/jupyterhub/anaconda/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1334: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [212]:
#Import K Neighbors Classifier
from sklearn.neighbors import KNeighborsClassifier

#Create and fit K Neighbors Classifier
knn = KNeighborsClassifier(n_neighbors=4).fit(X_train, y_train)

#Create predictions of K Neighbors Classifier
knn_y_pred =  knn.predict(X_test)

#Print confusion matrix and classification report
print(confusion_matrix(y_test, knn_y_pred))
print(classification_report(y_test, knn_y_pred))

[[  1   0   0   3   0   8   5   0   0   0   0   0   0   0]
 [  1  50   0   7   0  21   5   0   1   0   0   0   0   0]
 [  0   0   0   1   0   2   1   0   0   0   0   0   0   0]
 [  0   0   0   7   0  11   9   0   0   0   0   0   0   0]
 [  0   0   1   0   0   1   3   0   0   0   0   0   0   0]
 [  0   3   0   8   0  83  18   0   3   0   0   0   0   0]
 [  2   3   1  10   0  32 115   0   2   0   0   0   0   0]
 [  0   0   0   2   0   3   3   0   1   0   0   0   0   0]
 [  1   1   0  12   0   8  17   0   5   0   0   0   0   0]
 [  2   8   0   3   0  12   7   0   0   7   0   0   0   0]
 [  0   2   0   2   0  11   4   0   2   0   0   0   0   0]
 [  0   0   0   1   0   4   0   0   0   0   0   0   0   0]
 [  0   0   0   3   0   1   5   0   0   0   0   0   0   0]
 [  0   2   0   1   0   2   3   0   0   0   0   0   0   0]]
                 precision    recall  f1-score   support

     amerikaans       0.14      0.06      0.08        17
      aziatisch       0.72      0.59      0.65        85
 

/opt/jupyterhub/anaconda/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1334: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/jupyterhub/anaconda/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1334: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/jupyterhub/anaconda/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1334: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [213]:
#Import Logistic Regression
from sklearn.linear_model import LogisticRegression

#Create and fit Logistic Regression
lgr = LogisticRegression(multi_class='multinomial', solver = 'lbfgs').fit(X_train, y_train)

#Create predictions of Logistic Regression
lgr_y_pred =  lgr.predict(X_test)

#Print confusion matrix and classification report
print(confusion_matrix(y_test, lgr_y_pred))
print(classification_report(y_test, lgr_y_pred))

[[  3   0   0   0   0   7   5   0   1   1   0   0   0   0]
 [  0  73   0   0   0   9   2   0   0   1   0   0   0   0]
 [  0   1   0   0   0   3   0   0   0   0   0   0   0   0]
 [  0   1   0   5   0  10   8   0   3   0   0   0   0   0]
 [  0   0   0   1   0   0   2   0   2   0   0   0   0   0]
 [  0   3   0   3   0  89  17   0   2   1   0   0   0   0]
 [  0   0   0   2   0  11 147   0   5   0   0   0   0   0]
 [  0   0   0   0   0   2   0   1   3   0   3   0   0   0]
 [  0   1   0   1   0   8  14   2  15   0   2   0   1   0]
 [  0   1   0   0   0   4   1   0   0  32   1   0   0   0]
 [  0   7   0   0   0   3   1   0   5   0   4   0   1   0]
 [  0   0   0   0   0   4   1   0   0   0   0   0   0   0]
 [  0   0   0   0   0   2   1   0   2   1   0   0   3   0]
 [  0   2   0   0   0   0   4   0   0   2   0   0   0   0]]
                 precision    recall  f1-score   support

     amerikaans       1.00      0.18      0.30        17
      aziatisch       0.82      0.86      0.84        85
 

/opt/jupyterhub/anaconda/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1334: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/jupyterhub/anaconda/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1334: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/jupyterhub/anaconda/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1334: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


# persoon lust aziatisch niet en italiaans wel 

In [6]:
tags_ValidColumns_aziatisch = tags_ValidColumns[tags_ValidColumns["aziatisch"] == 1]
aziatischRecipes = tags_ValidColumns_aziatisch.index
aziatischIngredients = ValidColumns[ValidColumns.index.isin(aziatischRecipes.to_list())]
aziatischIngredients['y'] = 0
aziatischIngredients


/tmp/ipykernel_3855/791802141.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  aziatischIngredients['y'] = 0


(arachide)olie  \
recipe                                                               
'Leeuwenkoppen' van gehakt en kool                             0.0   
'Pho' met mihoen en ribeye                                     0.0   
10 minutennasi met ham en gebakken ei                          0.0   
Aardappel-groentecurry                                         0.0   
Aspergebroccoli met  sesam &amp; gepocheerde ki...             0.0   
...                                                            ...   
Zoetzure ribkarbonades met rijst                               0.0   
Zoetzuur varkensvlees met bosui                                0.0   
Zoetzuur varkensvlees met sesam-radijs                         0.0   
Zwaardvissteaks met tomatentartaar                             0.0   
‘Nasi’ met Hollandse soepgroente                               0.0   

                                                    (olijf)olie  \
recipe                                                            
'Leeuwenkoppen' van gehakt en kool                          0.0   
'Pho' met mihoen en ribeye                                  0.0   
10 minutennasi met ham en gebakken ei                       0.0   
Aardappel-groentecurry                                      0.0   
Aspergebroccoli met  sesam &amp; gepocheerde ki...          0.0   
...                                                         ...   
Zoetzure ribkarbonades met rijst                            0.0   
Zoetzuur varkensvlees met bosui                             0.0   
Zoetzuur varkensvlees met sesam-radijs                      0.0   
Zwaardvissteaks met tomatentartaar                          0.0   
‘Nasi’ met Hollandse soepgroente                            0.0   

                                                    Franse mosterd  \
recipe                                                               
'Leeuwenkoppen' van gehakt en kool                             0.0   
'Pho' met mihoen en ribeye                                     0.0   
10 minutennasi met ham en gebakken ei                          0.0   
Aardappel-groentecurry                                         0.0   
Aspergebroccoli met  sesam &amp; gepocheerde ki...             0.0   
...                                                            ...   
Zoetzure ribkarbonades met rijst                               0.0   
Zoetzuur varkensvlees met bosui                                0.0   
Zoetzuur varkensvlees met sesam-radijs                         0.0   
Zwaardvissteaks met tomatentartaar                             0.0   
‘Nasi’ met Hollandse soepgroente                               0.0   

                                                    Griekse yoghurt  \
recipe                                                                
'Leeuwenkoppen' van gehakt en kool                              0.0   
'Pho' met mihoen en ribeye                                      0.0   
10 minutennasi met ham en gebakken ei                           0.0   
Aardappel-groentecurry                                          0.0   
Aspergebroccoli met  sesam &amp; gepocheerde ki...              0.0   
...                                                             ...   
Zoetzure ribkarbonades met rijst                                0.0   
Zoetzuur varkensvlees met bosui                                 0.0   
Zoetzuur varkensvlees met sesam-radijs                          0.0   
Zwaardvissteaks met tomatentartaar                              0.0   
‘Nasi’ met Hollandse soepgroente                                0.0   

                                                    Japanse sojasaus  \
recipe                                                                 
'Leeuwenkoppen' van gehakt en kool                               1.0   
'Pho' met mihoen en ribeye                                       0.0   
10 minutennasi met ham en gebakken ei                            0.0   
Aardappel-groentecurry                                           0.0   
As

In [63]:
tags_ValidColumns_italiaans = tags_ValidColumns[tags_ValidColumns["italiaans"] == 1]
italiaansRecipes = tags_ValidColumns_italiaans.index
italiaansIngredients = ValidColumns[ValidColumns.index.isin(italiaansRecipes.to_list())]
#italiaansIngredients = italiaansIngredients.iloc[0: len(aziatischIngredients),:]
italiaansIngredients['y'] = 1
italiaansIngredients

/tmp/ipykernel_3855/3880851119.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  italiaansIngredients['y'] = 1


(arachide)olie  \
recipe                                                              
Aardappelbolognesegratin                                      0.0   
Aardappelsalade op z'n Italiaans                              0.0   
Antonio Carluccio's risotto met voorjaarsgroenten             0.0   
Antonio Carluccio’s pasta en doperwten                        0.0   
Arrabbiata met paprika en wodka                               0.0   
...                                                           ...   
Zomerse gnocchi met geroosterde trostomaten                   0.0   
Zomerse pastabowl                                             0.0   
Zomerse pastasalade met zalm en pestospread                   0.0   
Zomerse risotto met een zachtgekookt eitje                    0.0   
Zwarte tagliatelle met mosselen in tomatensaus                0.0   

                                                   (olijf)olie  \
recipe                                                           
Aardappelbolognesegratin                                   0.0   
Aardappelsalade op z'n Italiaans                           0.0   
Antonio Carluccio's risotto met voorjaarsgroenten          0.0   
Antonio Carluccio’s pasta en doperwten                     0.0   
Arrabbiata met paprika en wodka                            0.0   
...                                                        ...   
Zomerse gnocchi met geroosterde trostomaten                0.0   
Zomerse pastabowl                                          0.0   
Zomerse pastasalade met zalm en pestospread                0.0   
Zomerse risotto met een zachtgekookt eitje                 0.0   
Zwarte tagliatelle met mosselen in tomatensaus             0.0   

                                                   Franse mosterd  \
recipe                                                              
Aardappelbolognesegratin                                      0.0   
Aardappelsalade op z'n Italiaans                              0.0   
Antonio Carluccio's risotto met voorjaarsgroenten             0.0   
Antonio Carluccio’s pasta en doperwten                        0.0   
Arrabbiata met paprika en wodka                               0.0   
...                                                           ...   
Zomerse gnocchi met geroosterde trostomaten                   0.0   
Zomerse pastabowl                                             0.0   
Zomerse pastasalade met zalm en pestospread                   0.0   
Zomerse risotto met een zachtgekookt eitje                    0.0   
Zwarte tagliatelle met mosselen in tomatensaus                0.0   

                                                   Griekse yoghurt  \
recipe                                                               
Aardappelbolognesegratin                                       0.0   
Aardappelsalade op z'n Italiaans                               0.0   
Antonio Carluccio's risotto met voorjaarsgroenten              0.0   
Antonio Carluccio’s pasta en doperwten                         0.0   
Arrabbiata met paprika en wodka                                0.0   
...                                                            ...   
Zomerse gnocchi met geroosterde trostomaten                    0.0   
Zomerse pastabowl                                              0.0   
Zomerse pastasalade met zalm en pestospread                    0.0   
Zomerse risotto met een zachtgekookt eitje                     0.0   
Zwarte tagliatelle met mosselen in tomatensaus                 0.0   

                                                   Japanse sojasaus  \
recipe                                                                
Aardappelbolognesegratin                                        0.0   
Aardappelsalade op z'n Italiaans                                0.0   
Antonio Carluccio's risotto met voorjaarsgroenten               0.0   
Antonio Carluccio’s pasta en doperwten                          0.0   
Arrabbiata met paprika en wodka                            

In [64]:
data = pd.concat([italiaansIngredients,aziatischIngredients])
data = data.loc[:,data.sum() != 0][data.sum(axis=1) != 0]
X = data.iloc[:,:-1]
y = data.iloc[:,-1]
data

(arachide)olie  \
recipe                                                              
Aardappelbolognesegratin                                      0.0   
Aardappelsalade op z'n Italiaans                              0.0   
Antonio Carluccio's risotto met voorjaarsgroenten             0.0   
Antonio Carluccio’s pasta en doperwten                        0.0   
Arrabbiata met paprika en wodka                               0.0   
...                                                           ...   
Zoetzure ribkarbonades met rijst                              0.0   
Zoetzuur varkensvlees met bosui                               0.0   
Zoetzuur varkensvlees met sesam-radijs                        0.0   
Zwaardvissteaks met tomatentartaar                            0.0   
‘Nasi’ met Hollandse soepgroente                              0.0   

                                                   (olijf)olie  \
recipe                                                           
Aardappelbolognesegratin                                   0.0   
Aardappelsalade op z'n Italiaans                           0.0   
Antonio Carluccio's risotto met voorjaarsgroenten          0.0   
Antonio Carluccio’s pasta en doperwten                     0.0   
Arrabbiata met paprika en wodka                            0.0   
...                                                        ...   
Zoetzure ribkarbonades met rijst                           0.0   
Zoetzuur varkensvlees met bosui                            0.0   
Zoetzuur varkensvlees met sesam-radijs                     0.0   
Zwaardvissteaks met tomatentartaar                         0.0   
‘Nasi’ met Hollandse soepgroente                           0.0   

                                                   Franse mosterd  \
recipe                                                              
Aardappelbolognesegratin                                      0.0   
Aardappelsalade op z'n Italiaans                              0.0   
Antonio Carluccio's risotto met voorjaarsgroenten             0.0   
Antonio Carluccio’s pasta en doperwten                        0.0   
Arrabbiata met paprika en wodka                               0.0   
...                                                           ...   
Zoetzure ribkarbonades met rijst                              0.0   
Zoetzuur varkensvlees met bosui                               0.0   
Zoetzuur varkensvlees met sesam-radijs                        0.0   
Zwaardvissteaks met tomatentartaar                            0.0   
‘Nasi’ met Hollandse soepgroente                              0.0   

                                                   Griekse yoghurt  \
recipe                                                               
Aardappelbolognesegratin                                       0.0   
Aardappelsalade op z'n Italiaans                               0.0   
Antonio Carluccio's risotto met voorjaarsgroenten              0.0   
Antonio Carluccio’s pasta en doperwten                         0.0   
Arrabbiata met paprika en wodka                                0.0   
...                                                            ...   
Zoetzure ribkarbonades met rijst                               0.0   
Zoetzuur varkensvlees met bosui                                0.0   
Zoetzuur varkensvlees met sesam-radijs                         0.0   
Zwaardvissteaks met tomatentartaar                             0.0   
‘Nasi’ met Hollandse soepgroente                               0.0   

                                                   Japanse sojasaus  \
recipe                                                                
Aardappelbolognesegratin                                        0.0   
Aardappelsalade op z'n Italiaans                                0.0   
Antonio Carluccio's risotto met voorjaarsgroenten               0.0   
Antonio Carluccio’s pasta en doperwten                          0.0   
Arrabbiata met paprika en wodka                            

In [69]:
#Generate X_train, X_test, y_train, y_test
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4)#, random_state=42)

In [70]:
#Import Decision Tree Classifier
from sklearn import tree

#Create and fit Decision Tree Classifier
clf = tree.DecisionTreeClassifier(max_depth = 3).fit(X_train, y_train)

#Create predictions of Decision Tree Classifier
clf_y_pred =  clf.predict(X_test)

#Print confusion matrix and classification report
print(confusion_matrix(y_test, clf_y_pred))
print(classification_report(y_test, clf_y_pred))

[[128  51]
 [  7 231]]
              precision    recall  f1-score   support

           0       0.95      0.72      0.82       179
           1       0.82      0.97      0.89       238

    accuracy                           0.86       417
   macro avg       0.88      0.84      0.85       417
weighted avg       0.87      0.86      0.86       417



In [71]:
#Import Logistic Regression
from sklearn.linear_model import LogisticRegression

#Create and fit Logistic Regression
lgr = LogisticRegression(multi_class='multinomial', solver = 'lbfgs').fit(X_train, y_train)

#Create predictions of Logistic Regression
lgr_y_pred =  lgr.predict(X_test)

#Print confusion matrix and classification report
print(confusion_matrix(y_test, lgr_y_pred))
print(classification_report(y_test, lgr_y_pred))

[[168  11]
 [  7 231]]
              precision    recall  f1-score   support

           0       0.96      0.94      0.95       179
           1       0.95      0.97      0.96       238

    accuracy                           0.96       417
   macro avg       0.96      0.95      0.96       417
weighted avg       0.96      0.96      0.96       417



In [72]:
#Import K Neighbors Classifier
from sklearn.neighbors import KNeighborsClassifier

#Create and fit K Neighbors Classifier
knn = KNeighborsClassifier(n_neighbors=4).fit(X_train, y_train)

#Create predictions of K Neighbors Classifier
knn_y_pred =  knn.predict(X_test)

#Print confusion matrix and classification report
print(confusion_matrix(y_test, knn_y_pred))
print(classification_report(y_test, knn_y_pred))

[[150  29]
 [ 26 212]]
              precision    recall  f1-score   support

           0       0.85      0.84      0.85       179
           1       0.88      0.89      0.89       238

    accuracy                           0.87       417
   macro avg       0.87      0.86      0.87       417
weighted avg       0.87      0.87      0.87       417



In [38]:
 y_train.sum()

37.0

In [37]:
y_test.sum()

7.0

In [26]:
X_test.describe()

(arachide)olie  (olijf)olie  Franse mosterd  Griekse yoghurt  \
count      207.000000   207.000000           207.0       207.000000   
mean         0.014493     0.028986             0.0         0.009662   
std          0.119800     0.168172             0.0         0.098056   
min          0.000000     0.000000             0.0         0.000000   
25%          0.000000     0.000000             0.0         0.000000   
50%          0.000000     0.000000             0.0         0.000000   
75%          0.000000     0.000000             0.0         0.000000   
max          1.000000     1.000000             0.0         1.000000   

       Japanse sojasaus  Parmezaanse kaas  Parmigiano Reggiano  \
count        207.000000        207.000000           207.000000   
mean           0.043478          0.028986             0.053140   
std            0.204425          0.168172             0.224857   
min            0.000000          0.000000             0.000000   
25%            0.000000          0.000000             0.000000   
50%            0.000000          0.000000             0.000000   
75%            0.000000          0.000000             0.000000   
max            1.000000          1.000000             1.000000   

       Pecorino Romano (kaas)  Tasty Tom trostomaat  appelciderazijn  ...  \
count              207.000000            207.000000            207.0  ...   
mean                 0.014493              0.014493              0.0  ...   
std                  0.119800              0.119800              0.0  ...   
min                  0.000000              0.000000              0.0  ...   
25%                  0.000000              0.000000              0.0  ...   
50%                  0.000000              0.000000              0.0  ...   
75%                  0.000000              0.000000              0.0  ...   
max                  1.000000              1.000000              0.0  ...   

       volle melk       water  winterpeen  witlof  witte kaas 45+  \
count       207.0  207.000000  207.000000   207.0      207.000000   
mean          0.0    0.086957    0.062802     0.0        0.004831   
std           0.0    0.282454    0.243195     0.0        0.069505   
min           0.0    0.000000    0.000000     0.0        0.000000   
25%           0.0    0.000000    0.000000     0.0        0.000000   
50%           0.0    0.000000    0.000000     0.0        0.000000   
75%           0.0    0.000000    0.000000     0.0        0.000000   
max           0.0    1.000000    1.000000     0.0        1.000000   

       witte rijst  zilvervliesrijst  zoete aardappel  zoete chilisaus  \
count   207.000000        207.000000       207.000000       207.000000   
mean      0.019324          0.009662         0.024155         0.028986   
std       0.137994          0.098056         0.153901         0.168172   
min       0.000000          0.000000         0.000000         0.000000   
25%       0.000000          0.000000         0.000000         0.000000   
50%       0.000000          0.000000         0.000000         0.000000   
75%       0.000000          0.000000         0.000000         0.000000   
max       1.000000          1.000000         1.000000         1.000000   

       zonnebloemolie  
count      207.000000  
mean         0.082126  
std          0.275222  
min          0.000000  
25%          0.000000  
50%          0.000000  
75%          0.000000  
max          1.000000  

[8 rows x 164 columns]

In [21]:
X_train.describe()

(arachide)olie  (olijf)olie  Franse mosterd  Griekse yoghurt  \
count       828.00000   828.000000      828.000000       828.000000   
mean          0.02657     0.016908        0.004831         0.010870   
std           0.16092     0.129006        0.069379         0.103752   
min           0.00000     0.000000        0.000000         0.000000   
25%           0.00000     0.000000        0.000000         0.000000   
50%           0.00000     0.000000        0.000000         0.000000   
75%           0.00000     0.000000        0.000000         0.000000   
max           1.00000     1.000000        1.000000         1.000000   

       Japanse sojasaus  Parmezaanse kaas  Parmigiano Reggiano  \
count        828.000000        828.000000           828.000000   
mean           0.027778          0.028986             0.065217   
std            0.164435          0.167867             0.247058   
min            0.000000          0.000000             0.000000   
25%            0.000000          0.000000             0.000000   
50%            0.000000          0.000000             0.000000   
75%            0.000000          0.000000             0.000000   
max            1.000000          1.000000             1.000000   

       Pecorino Romano (kaas)  Tasty Tom trostomaat  appelciderazijn  ...  \
count              828.000000            828.000000       828.000000  ...   
mean                 0.021739              0.014493         0.003623  ...   
std                  0.145919              0.119583         0.060120  ...   
min                  0.000000              0.000000         0.000000  ...   
25%                  0.000000              0.000000         0.000000  ...   
50%                  0.000000              0.000000         0.000000  ...   
75%                  0.000000              0.000000         0.000000  ...   
max                  1.000000              1.000000         1.000000  ...   

       volle melk       water  winterpeen      witlof  witte kaas 45+  \
count  828.000000  828.000000  828.000000  828.000000      828.000000   
mean     0.006039    0.077295    0.047101    0.004831        0.002415   
std      0.077521    0.267220    0.211984    0.069379        0.049118   
min      0.000000    0.000000    0.000000    0.000000        0.000000   
25%      0.000000    0.000000    0.000000    0.000000        0.000000   
50%      0.000000    0.000000    0.000000    0.000000        0.000000   
75%      0.000000    0.000000    0.000000    0.000000        0.000000   
max      1.000000    1.000000    1.000000    1.000000        1.000000   

       witte rijst  zilvervliesrijst  zoete aardappel  zoete chilisaus  \
count   828.000000        828.000000       828.000000       828.000000   
mean      0.012077          0.018116         0.009662         0.014493   
std       0.109297          0.133451         0.097878         0.119583   
min       0.000000          0.000000         0.000000         0.000000   
25%       0.000000          0.000000         0.000000         0.000000   
50%       0.000000          0.000000         0.000000         0.000000   
75%       0.000000          0.000000         0.000000         0.000000   
max       1.000000          1.000000         1.000000         1.000000   

       zonnebloemolie  
count      828.000000  
mean         0.088164  
std          0.283705  
min          0.000000  
25%          0.000000  
50%          0.000000  
75%          0.000000  
max          1.000000  

[8 rows x 164 columns]